services:
  ytdlp:
    image: ${IMAGE}
    container_name: ytdlp
    volumes:
      - ./:/data
    environment:
      - PROXY=${PROXY}
  whisper:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: ${IMAGE}
    container_name: whisper
    volumes:
      - ./:/data
    environment:
      - PROXY=${PROXY}
  translate:
    image: ${IMAGE}
    container_name: translate
    volumes:
      - ./:/data
    environment:
      - PROXY=${PROXY}
